// Copyright (c) 2017 Sony Corporation. All Rights Reserved.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// *WARNING*
// THIS FILE IS AUTO-GENERATED BY CODE GENERATOR.
// PLEASE DO NOT EDIT THIS FILE BY HAND!

#ifndef H_VALIDATION_INFERENCE_H__
#define H_VALIDATION_INFERENCE_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

// All information for inference stores into context buffer.
// Detailed structure of context is invisible from user.

/// Allocate memories and initialize buffers.
void* nnablart_validation_allocate_context(void** params);

/// Free all memories in the context
int nnablart_validation_free_context(void* context);

/// Number of input buffers.
#define NNABLART_VALIDATION_NUM_OF_INPUT_BUFFERS (1)
/// Input buffer sizes.
#define NNABLART_VALIDATION_INPUT0_SIZE (784)
/// Pointer of allocated buffer.
float* nnablart_validation_input_buffer(void* context, int index);

/// Number of output buffers.
#define NNABLART_VALIDATION_NUM_OF_OUTPUT_BUFFERS (1)
/// Output buffer sizes.
#define NNABLART_VALIDATION_OUTPUT0_SIZE (10)
/// Pointer of allocated buffer.
float* nnablart_validation_output_buffer(void* context, int index);
/// Number of parameter buffers.
#define NNABLART_VALIDATION_NUM_OF_PARAM_BUFFERS (8)
/// Parameter buffer sizes.
#define NNABLART_VALIDATION_PARAM0_SIZE (400)
#define NNABLART_VALIDATION_PARAM1_SIZE (16)
#define NNABLART_VALIDATION_PARAM2_SIZE (6400)
#define NNABLART_VALIDATION_PARAM3_SIZE (16)
#define NNABLART_VALIDATION_PARAM4_SIZE (12800)
#define NNABLART_VALIDATION_PARAM5_SIZE (50)
#define NNABLART_VALIDATION_PARAM6_SIZE (500)
#define NNABLART_VALIDATION_PARAM7_SIZE (10)
/// Pointer of allocated buffer.
float* nnablart_validation_param_buffer(void* context, int index);

/// Exec inference
int nnablart_validation_inference(void* context);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif //H_VALIDATION_INFERENCE_H__
