// Copyright (c) 2017 Sony Corporation. All Rights Reserved.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// *WARNING*
// THIS FILE IS AUTO-GENERATED BY CODE GENERATOR.
// PLEASE DO NOT EDIT THIS FILE BY HAND!

#include "Validation_inference.h"

#include <nnablart/functions.h>
#include <string.h>

typedef struct {
    void *buffer_pool[2];
    void *param_pool[8];
    rt_buffer_allocate_type_t variable_buffers_allocate_type[20];

    // Variables
    rt_variable_t v0; ///< x
    int v0_shape[4];
    rt_variable_t v1; ///< MulScalar_Output
    int v1_shape[4];
    rt_variable_t v2; ///< conv1/conv/W
    int v2_shape[4];
    rt_variable_t v3; ///< conv1/conv/b
    int v3_shape[1];
    rt_variable_t v4; ///< Convolution_Output
    int v4_shape[4];
    rt_variable_t v5; ///< MaxPooling_Output
    int v5_shape[4];
    rt_variable_t v6; ///< ReLU_Output
    int v6_shape[4];
    rt_variable_t v7; ///< conv2/conv/W
    int v7_shape[4];
    rt_variable_t v8; ///< conv2/conv/b
    int v8_shape[1];
    rt_variable_t v9; ///< Convolution_2_Output
    int v9_shape[4];
    rt_variable_t v10; ///< MaxPooling_2_Output
    int v10_shape[4];
    rt_variable_t v11; ///< ReLU_2_Output
    int v11_shape[4];
    rt_variable_t v12; ///< fc3/affine/W
    int v12_shape[2];
    rt_variable_t v13; ///< fc3/affine/b
    int v13_shape[1];
    rt_variable_t v14; ///< Affine_Output
    int v14_shape[2];
    rt_variable_t v15; ///< ReLU_3_Output
    int v15_shape[2];
    rt_variable_t v16; ///< fc4/affine/W
    int v16_shape[2];
    rt_variable_t v17; ///< fc4/affine/b
    int v17_shape[1];
    rt_variable_t v18; ///< Affine_2_Output
    int v18_shape[2];
    rt_variable_t v19; ///< y
    int v19_shape[2];

    // Functions
    rt_function_t f0; ///< MulScalar
    rt_variable_t* f0_inputs[1];
    rt_variable_t* f0_outputs[1];
    mul_scalar_local_context_t *f0_local_context;
    rt_function_t f1; ///< Convolution
    rt_variable_t* f1_inputs[3];
    rt_variable_t* f1_outputs[1];
    convolution_local_context_t *f1_local_context;
    int f1_local_context_shape_pad[2];
    int f1_local_context_shape_stride[2];
    int f1_local_context_shape_dilation[2];
    rt_function_t f2; ///< MaxPooling
    rt_variable_t* f2_inputs[1];
    rt_variable_t* f2_outputs[1];
    max_pooling_local_context_t *f2_local_context;
    int f2_local_context_shape_kernel[2];
    int f2_local_context_shape_stride[2];
    int f2_local_context_shape_pad[2];
    rt_function_t f3; ///< ReLU
    rt_variable_t* f3_inputs[1];
    rt_variable_t* f3_outputs[1];
    relu_local_context_t *f3_local_context;
    rt_function_t f4; ///< Convolution
    rt_variable_t* f4_inputs[3];
    rt_variable_t* f4_outputs[1];
    convolution_local_context_t *f4_local_context;
    int f4_local_context_shape_pad[2];
    int f4_local_context_shape_stride[2];
    int f4_local_context_shape_dilation[2];
    rt_function_t f5; ///< MaxPooling
    rt_variable_t* f5_inputs[1];
    rt_variable_t* f5_outputs[1];
    max_pooling_local_context_t *f5_local_context;
    int f5_local_context_shape_kernel[2];
    int f5_local_context_shape_stride[2];
    int f5_local_context_shape_pad[2];
    rt_function_t f6; ///< ReLU
    rt_variable_t* f6_inputs[1];
    rt_variable_t* f6_outputs[1];
    relu_local_context_t *f6_local_context;
    rt_function_t f7; ///< Affine
    rt_variable_t* f7_inputs[3];
    rt_variable_t* f7_outputs[1];
    affine_local_context_t *f7_local_context;
    rt_function_t f8; ///< ReLU
    rt_variable_t* f8_inputs[1];
    rt_variable_t* f8_outputs[1];
    relu_local_context_t *f8_local_context;
    rt_function_t f9; ///< Affine
    rt_variable_t* f9_inputs[3];
    rt_variable_t* f9_outputs[1];
    affine_local_context_t *f9_local_context;
    rt_function_t f10; ///< Softmax
    rt_variable_t* f10_inputs[1];
    rt_variable_t* f10_outputs[1];
    softmax_local_context_t *f10_local_context;
} nnablart_validation_local_context_t;

int actual_buf_sizes[2] = {
    1179648,
    1179648,
};

void *(*rt_variable_malloc_func)(size_t size) = malloc;
void (*rt_variable_free_func)(void *ptr) = free;

void *(*rt_malloc_func)(size_t size) = malloc;
void (*rt_free_func)(void *ptr) = free;


void* nnablart_validation_allocate_context(void** params)
{
    nnablart_validation_local_context_t* c = malloc(sizeof(nnablart_validation_local_context_t));
    // Variable buffer
    for (int i = 0; i < 2; i++) {
        c->buffer_pool[i] = malloc(sizeof(float) * actual_buf_sizes[i]);
        memset(c->buffer_pool[i], 0, sizeof(float) * actual_buf_sizes[i]);
    }
    if(params) {
        c->variable_buffers_allocate_type[2] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[0] = *params++;
        c->variable_buffers_allocate_type[3] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[1] = *params++;
        c->variable_buffers_allocate_type[7] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[2] = *params++;
        c->variable_buffers_allocate_type[8] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[3] = *params++;
        c->variable_buffers_allocate_type[12] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[4] = *params++;
        c->variable_buffers_allocate_type[13] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[5] = *params++;
        c->variable_buffers_allocate_type[16] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[6] = *params++;
        c->variable_buffers_allocate_type[17] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[7] = *params++;
    } else {
        c->variable_buffers_allocate_type[2] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[0] = *params++;
        c->param_pool[0] = malloc(sizeof(float) * 400);
        c->variable_buffers_allocate_type[3] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[1] = *params++;
        c->param_pool[1] = malloc(sizeof(float) * 16);
        c->variable_buffers_allocate_type[7] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[2] = *params++;
        c->param_pool[2] = malloc(sizeof(float) * 6400);
        c->variable_buffers_allocate_type[8] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[3] = *params++;
        c->param_pool[3] = malloc(sizeof(float) * 16);
        c->variable_buffers_allocate_type[12] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[4] = *params++;
        c->param_pool[4] = malloc(sizeof(float) * 12800);
        c->variable_buffers_allocate_type[13] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[5] = *params++;
        c->param_pool[5] = malloc(sizeof(float) * 50);
        c->variable_buffers_allocate_type[16] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[6] = *params++;
        c->param_pool[6] = malloc(sizeof(float) * 500);
        c->variable_buffers_allocate_type[17] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[7] = *params++;
        c->param_pool[7] = malloc(sizeof(float) * 10);
    }

    // Variables
    // x
    (c->v0).type = NN_DATA_TYPE_FLOAT;
    (c->v0).shape.size = 4;
    c->v0_shape[0] = 128;
    c->v0_shape[1] = 1;
    c->v0_shape[2] = 28;
    c->v0_shape[3] = 28;
    (c->v0).shape.data = c->v0_shape;
    (c->v0).data = c->buffer_pool[0];
    // MulScalar_Output
    (c->v1).type = NN_DATA_TYPE_FLOAT;
    (c->v1).shape.size = 4;
    c->v1_shape[0] = 128;
    c->v1_shape[1] = 1;
    c->v1_shape[2] = 28;
    c->v1_shape[3] = 28;
    (c->v1).shape.data = c->v1_shape;
    (c->v1).data = c->buffer_pool[1];
    // conv1/conv/W
    (c->v2).type = NN_DATA_TYPE_FLOAT;
    (c->v2).shape.size = 4;
    c->v2_shape[0] = 16;
    c->v2_shape[1] = 1;
    c->v2_shape[2] = 5;
    c->v2_shape[3] = 5;
    (c->v2).shape.data = c->v2_shape;
    (c->v2).data = c->param_pool[0];
    // conv1/conv/b
    (c->v3).type = NN_DATA_TYPE_FLOAT;
    (c->v3).shape.size = 1;
    c->v3_shape[0] = 16;
    (c->v3).shape.data = c->v3_shape;
    (c->v3).data = c->param_pool[1];
    // Convolution_Output
    (c->v4).type = NN_DATA_TYPE_FLOAT;
    (c->v4).shape.size = 4;
    c->v4_shape[0] = 128;
    c->v4_shape[1] = 16;
    c->v4_shape[2] = 24;
    c->v4_shape[3] = 24;
    (c->v4).shape.data = c->v4_shape;
    (c->v4).data = c->buffer_pool[0];
    // MaxPooling_Output
    (c->v5).type = NN_DATA_TYPE_FLOAT;
    (c->v5).shape.size = 4;
    c->v5_shape[0] = 128;
    c->v5_shape[1] = 16;
    c->v5_shape[2] = 12;
    c->v5_shape[3] = 12;
    (c->v5).shape.data = c->v5_shape;
    (c->v5).data = c->buffer_pool[1];
    // ReLU_Output
    (c->v6).type = NN_DATA_TYPE_FLOAT;
    (c->v6).shape.size = 4;
    c->v6_shape[0] = 128;
    c->v6_shape[1] = 16;
    c->v6_shape[2] = 12;
    c->v6_shape[3] = 12;
    (c->v6).shape.data = c->v6_shape;
    (c->v6).data = c->buffer_pool[0];
    // conv2/conv/W
    (c->v7).type = NN_DATA_TYPE_FLOAT;
    (c->v7).shape.size = 4;
    c->v7_shape[0] = 16;
    c->v7_shape[1] = 16;
    c->v7_shape[2] = 5;
    c->v7_shape[3] = 5;
    (c->v7).shape.data = c->v7_shape;
    (c->v7).data = c->param_pool[2];
    // conv2/conv/b
    (c->v8).type = NN_DATA_TYPE_FLOAT;
    (c->v8).shape.size = 1;
    c->v8_shape[0] = 16;
    (c->v8).shape.data = c->v8_shape;
    (c->v8).data = c->param_pool[3];
    // Convolution_2_Output
    (c->v9).type = NN_DATA_TYPE_FLOAT;
    (c->v9).shape.size = 4;
    c->v9_shape[0] = 128;
    c->v9_shape[1] = 16;
    c->v9_shape[2] = 8;
    c->v9_shape[3] = 8;
    (c->v9).shape.data = c->v9_shape;
    (c->v9).data = c->buffer_pool[1];
    // MaxPooling_2_Output
    (c->v10).type = NN_DATA_TYPE_FLOAT;
    (c->v10).shape.size = 4;
    c->v10_shape[0] = 128;
    c->v10_shape[1] = 16;
    c->v10_shape[2] = 4;
    c->v10_shape[3] = 4;
    (c->v10).shape.data = c->v10_shape;
    (c->v10).data = c->buffer_pool[0];
    // ReLU_2_Output
    (c->v11).type = NN_DATA_TYPE_FLOAT;
    (c->v11).shape.size = 4;
    c->v11_shape[0] = 128;
    c->v11_shape[1] = 16;
    c->v11_shape[2] = 4;
    c->v11_shape[3] = 4;
    (c->v11).shape.data = c->v11_shape;
    (c->v11).data = c->buffer_pool[1];
    // fc3/affine/W
    (c->v12).type = NN_DATA_TYPE_FLOAT;
    (c->v12).shape.size = 2;
    c->v12_shape[0] = 256;
    c->v12_shape[1] = 50;
    (c->v12).shape.data = c->v12_shape;
    (c->v12).data = c->param_pool[4];
    // fc3/affine/b
    (c->v13).type = NN_DATA_TYPE_FLOAT;
    (c->v13).shape.size = 1;
    c->v13_shape[0] = 50;
    (c->v13).shape.data = c->v13_shape;
    (c->v13).data = c->param_pool[5];
    // Affine_Output
    (c->v14).type = NN_DATA_TYPE_FLOAT;
    (c->v14).shape.size = 2;
    c->v14_shape[0] = 128;
    c->v14_shape[1] = 50;
    (c->v14).shape.data = c->v14_shape;
    (c->v14).data = c->buffer_pool[0];
    // ReLU_3_Output
    (c->v15).type = NN_DATA_TYPE_FLOAT;
    (c->v15).shape.size = 2;
    c->v15_shape[0] = 128;
    c->v15_shape[1] = 50;
    (c->v15).shape.data = c->v15_shape;
    (c->v15).data = c->buffer_pool[1];
    // fc4/affine/W
    (c->v16).type = NN_DATA_TYPE_FLOAT;
    (c->v16).shape.size = 2;
    c->v16_shape[0] = 50;
    c->v16_shape[1] = 10;
    (c->v16).shape.data = c->v16_shape;
    (c->v16).data = c->param_pool[6];
    // fc4/affine/b
    (c->v17).type = NN_DATA_TYPE_FLOAT;
    (c->v17).shape.size = 1;
    c->v17_shape[0] = 10;
    (c->v17).shape.data = c->v17_shape;
    (c->v17).data = c->param_pool[7];
    // Affine_2_Output
    (c->v18).type = NN_DATA_TYPE_FLOAT;
    (c->v18).shape.size = 2;
    c->v18_shape[0] = 128;
    c->v18_shape[1] = 10;
    (c->v18).shape.data = c->v18_shape;
    (c->v18).data = c->buffer_pool[0];
    // y
    (c->v19).type = NN_DATA_TYPE_FLOAT;
    (c->v19).shape.size = 2;
    c->v19_shape[0] = 128;
    c->v19_shape[1] = 10;
    (c->v19).shape.data = c->v19_shape;
    (c->v19).data = c->buffer_pool[1];

    // Functions
    // MulScalar
    c->f0_local_context = malloc(sizeof(mul_scalar_local_context_t));
    (c->f0).num_of_inputs = 1;
    (c->f0_inputs)[0] = &(c->v0);
    (c->f0).inputs = c->f0_inputs;
    (c->f0).num_of_outputs = 1;
    (c->f0_outputs)[0] = &(c->v1);
    (c->f0).outputs = c->f0_outputs;
    (c->f0).local_context = c->f0_local_context;
    (c->f0_local_context)->val = 0.00392156862745098;
    allocate_mul_scalar_local_context(&(c->f0));
    // Convolution
    c->f1_local_context = malloc(sizeof(convolution_local_context_t));
    (c->f1).num_of_inputs = 3;
    (c->f1_inputs)[0] = &(c->v1);
    (c->f1_inputs)[1] = &(c->v2);
    (c->f1_inputs)[2] = &(c->v3);
    (c->f1).inputs = c->f1_inputs;
    (c->f1).num_of_outputs = 1;
    (c->f1_outputs)[0] = &(c->v4);
    (c->f1).outputs = c->f1_outputs;
    (c->f1).local_context = c->f1_local_context;
    (c->f1_local_context)->base_axis = 1;
    rt_list_t arg_f1_pad;
    arg_f1_pad.size = 2;
    arg_f1_pad.data = c->f1_local_context_shape_pad;
    arg_f1_pad.data[0] = 0;
    arg_f1_pad.data[1] = 0;
    (c->f1_local_context)->pad = arg_f1_pad;
    rt_list_t arg_f1_stride;
    arg_f1_stride.size = 2;
    arg_f1_stride.data = c->f1_local_context_shape_stride;
    arg_f1_stride.data[0] = 1;
    arg_f1_stride.data[1] = 1;
    (c->f1_local_context)->stride = arg_f1_stride;
    rt_list_t arg_f1_dilation;
    arg_f1_dilation.size = 2;
    arg_f1_dilation.data = c->f1_local_context_shape_dilation;
    arg_f1_dilation.data[0] = 1;
    arg_f1_dilation.data[1] = 1;
    (c->f1_local_context)->dilation = arg_f1_dilation;
    (c->f1_local_context)->group = 1;
    allocate_convolution_local_context(&(c->f1));
    // MaxPooling
    c->f2_local_context = malloc(sizeof(max_pooling_local_context_t));
    (c->f2).num_of_inputs = 1;
    (c->f2_inputs)[0] = &(c->v4);
    (c->f2).inputs = c->f2_inputs;
    (c->f2).num_of_outputs = 1;
    (c->f2_outputs)[0] = &(c->v5);
    (c->f2).outputs = c->f2_outputs;
    (c->f2).local_context = c->f2_local_context;
    rt_list_t arg_f2_kernel;
    arg_f2_kernel.size = 2;
    arg_f2_kernel.data = c->f2_local_context_shape_kernel;
    arg_f2_kernel.data[0] = 2;
    arg_f2_kernel.data[1] = 2;
    (c->f2_local_context)->kernel = arg_f2_kernel;
    rt_list_t arg_f2_stride;
    arg_f2_stride.size = 2;
    arg_f2_stride.data = c->f2_local_context_shape_stride;
    arg_f2_stride.data[0] = 2;
    arg_f2_stride.data[1] = 2;
    (c->f2_local_context)->stride = arg_f2_stride;
    (c->f2_local_context)->ignore_border = 1;
    rt_list_t arg_f2_pad;
    arg_f2_pad.size = 2;
    arg_f2_pad.data = c->f2_local_context_shape_pad;
    arg_f2_pad.data[0] = 0;
    arg_f2_pad.data[1] = 0;
    (c->f2_local_context)->pad = arg_f2_pad;
    allocate_max_pooling_local_context(&(c->f2));
    // ReLU
    c->f3_local_context = malloc(sizeof(relu_local_context_t));
    (c->f3).num_of_inputs = 1;
    (c->f3_inputs)[0] = &(c->v5);
    (c->f3).inputs = c->f3_inputs;
    (c->f3).num_of_outputs = 1;
    (c->f3_outputs)[0] = &(c->v6);
    (c->f3).outputs = c->f3_outputs;
    (c->f3).local_context = c->f3_local_context;
    (c->f3_local_context)->inplace = 1;
    allocate_relu_local_context(&(c->f3));
    // Convolution
    c->f4_local_context = malloc(sizeof(convolution_local_context_t));
    (c->f4).num_of_inputs = 3;
    (c->f4_inputs)[0] = &(c->v6);
    (c->f4_inputs)[1] = &(c->v7);
    (c->f4_inputs)[2] = &(c->v8);
    (c->f4).inputs = c->f4_inputs;
    (c->f4).num_of_outputs = 1;
    (c->f4_outputs)[0] = &(c->v9);
    (c->f4).outputs = c->f4_outputs;
    (c->f4).local_context = c->f4_local_context;
    (c->f4_local_context)->base_axis = 1;
    rt_list_t arg_f4_pad;
    arg_f4_pad.size = 2;
    arg_f4_pad.data = c->f4_local_context_shape_pad;
    arg_f4_pad.data[0] = 0;
    arg_f4_pad.data[1] = 0;
    (c->f4_local_context)->pad = arg_f4_pad;
    rt_list_t arg_f4_stride;
    arg_f4_stride.size = 2;
    arg_f4_stride.data = c->f4_local_context_shape_stride;
    arg_f4_stride.data[0] = 1;
    arg_f4_stride.data[1] = 1;
    (c->f4_local_context)->stride = arg_f4_stride;
    rt_list_t arg_f4_dilation;
    arg_f4_dilation.size = 2;
    arg_f4_dilation.data = c->f4_local_context_shape_dilation;
    arg_f4_dilation.data[0] = 1;
    arg_f4_dilation.data[1] = 1;
    (c->f4_local_context)->dilation = arg_f4_dilation;
    (c->f4_local_context)->group = 1;
    allocate_convolution_local_context(&(c->f4));
    // MaxPooling
    c->f5_local_context = malloc(sizeof(max_pooling_local_context_t));
    (c->f5).num_of_inputs = 1;
    (c->f5_inputs)[0] = &(c->v9);
    (c->f5).inputs = c->f5_inputs;
    (c->f5).num_of_outputs = 1;
    (c->f5_outputs)[0] = &(c->v10);
    (c->f5).outputs = c->f5_outputs;
    (c->f5).local_context = c->f5_local_context;
    rt_list_t arg_f5_kernel;
    arg_f5_kernel.size = 2;
    arg_f5_kernel.data = c->f5_local_context_shape_kernel;
    arg_f5_kernel.data[0] = 2;
    arg_f5_kernel.data[1] = 2;
    (c->f5_local_context)->kernel = arg_f5_kernel;
    rt_list_t arg_f5_stride;
    arg_f5_stride.size = 2;
    arg_f5_stride.data = c->f5_local_context_shape_stride;
    arg_f5_stride.data[0] = 2;
    arg_f5_stride.data[1] = 2;
    (c->f5_local_context)->stride = arg_f5_stride;
    (c->f5_local_context)->ignore_border = 1;
    rt_list_t arg_f5_pad;
    arg_f5_pad.size = 2;
    arg_f5_pad.data = c->f5_local_context_shape_pad;
    arg_f5_pad.data[0] = 0;
    arg_f5_pad.data[1] = 0;
    (c->f5_local_context)->pad = arg_f5_pad;
    allocate_max_pooling_local_context(&(c->f5));
    // ReLU
    c->f6_local_context = malloc(sizeof(relu_local_context_t));
    (c->f6).num_of_inputs = 1;
    (c->f6_inputs)[0] = &(c->v10);
    (c->f6).inputs = c->f6_inputs;
    (c->f6).num_of_outputs = 1;
    (c->f6_outputs)[0] = &(c->v11);
    (c->f6).outputs = c->f6_outputs;
    (c->f6).local_context = c->f6_local_context;
    (c->f6_local_context)->inplace = 1;
    allocate_relu_local_context(&(c->f6));
    // Affine
    c->f7_local_context = malloc(sizeof(affine_local_context_t));
    (c->f7).num_of_inputs = 3;
    (c->f7_inputs)[0] = &(c->v11);
    (c->f7_inputs)[1] = &(c->v12);
    (c->f7_inputs)[2] = &(c->v13);
    (c->f7).inputs = c->f7_inputs;
    (c->f7).num_of_outputs = 1;
    (c->f7_outputs)[0] = &(c->v14);
    (c->f7).outputs = c->f7_outputs;
    (c->f7).local_context = c->f7_local_context;
    (c->f7_local_context)->base_axis = 1;
    allocate_affine_local_context(&(c->f7));
    // ReLU
    c->f8_local_context = malloc(sizeof(relu_local_context_t));
    (c->f8).num_of_inputs = 1;
    (c->f8_inputs)[0] = &(c->v14);
    (c->f8).inputs = c->f8_inputs;
    (c->f8).num_of_outputs = 1;
    (c->f8_outputs)[0] = &(c->v15);
    (c->f8).outputs = c->f8_outputs;
    (c->f8).local_context = c->f8_local_context;
    (c->f8_local_context)->inplace = 1;
    allocate_relu_local_context(&(c->f8));
    // Affine
    c->f9_local_context = malloc(sizeof(affine_local_context_t));
    (c->f9).num_of_inputs = 3;
    (c->f9_inputs)[0] = &(c->v15);
    (c->f9_inputs)[1] = &(c->v16);
    (c->f9_inputs)[2] = &(c->v17);
    (c->f9).inputs = c->f9_inputs;
    (c->f9).num_of_outputs = 1;
    (c->f9_outputs)[0] = &(c->v18);
    (c->f9).outputs = c->f9_outputs;
    (c->f9).local_context = c->f9_local_context;
    (c->f9_local_context)->base_axis = 1;
    allocate_affine_local_context(&(c->f9));
    // Softmax
    c->f10_local_context = malloc(sizeof(softmax_local_context_t));
    (c->f10).num_of_inputs = 1;
    (c->f10_inputs)[0] = &(c->v18);
    (c->f10).inputs = c->f10_inputs;
    (c->f10).num_of_outputs = 1;
    (c->f10_outputs)[0] = &(c->v19);
    (c->f10).outputs = c->f10_outputs;
    (c->f10).local_context = c->f10_local_context;
    (c->f10_local_context)->axis = 1;
    allocate_softmax_local_context(&(c->f10));
    return (void*)c;
}

int nnablart_validation_free_context(void* context)
{
    nnablart_validation_local_context_t* c = (nnablart_validation_local_context_t*)context;

    for (int i = 0; i < 2; i++) {
        free(c->buffer_pool[i]);
    }
    if(c->variable_buffers_allocate_type[2] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[0]);
    }
    if(c->variable_buffers_allocate_type[3] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[1]);
    }
    if(c->variable_buffers_allocate_type[7] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[2]);
    }
    if(c->variable_buffers_allocate_type[8] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[3]);
    }
    if(c->variable_buffers_allocate_type[12] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[4]);
    }
    if(c->variable_buffers_allocate_type[13] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[5]);
    }
    if(c->variable_buffers_allocate_type[16] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[6]);
    }
    if(c->variable_buffers_allocate_type[17] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[7]);
    }
    free_mul_scalar_local_context(&(c->f0));
    if (c->f0.local_context != 0) {
        rt_free_func(c->f0.local_context);
        c->f0.local_context = 0;
    }
    free_convolution_local_context(&(c->f1));
    if (c->f1.local_context != 0) {
        rt_free_func(c->f1.local_context);
        c->f1.local_context = 0;
    }
    free_max_pooling_local_context(&(c->f2));
    if (c->f2.local_context != 0) {
        rt_free_func(c->f2.local_context);
        c->f2.local_context = 0;
    }
    free_relu_local_context(&(c->f3));
    if (c->f3.local_context != 0) {
        rt_free_func(c->f3.local_context);
        c->f3.local_context = 0;
    }
    free_convolution_local_context(&(c->f4));
    if (c->f4.local_context != 0) {
        rt_free_func(c->f4.local_context);
        c->f4.local_context = 0;
    }
    free_max_pooling_local_context(&(c->f5));
    if (c->f5.local_context != 0) {
        rt_free_func(c->f5.local_context);
        c->f5.local_context = 0;
    }
    free_relu_local_context(&(c->f6));
    if (c->f6.local_context != 0) {
        rt_free_func(c->f6.local_context);
        c->f6.local_context = 0;
    }
    free_affine_local_context(&(c->f7));
    if (c->f7.local_context != 0) {
        rt_free_func(c->f7.local_context);
        c->f7.local_context = 0;
    }
    free_relu_local_context(&(c->f8));
    if (c->f8.local_context != 0) {
        rt_free_func(c->f8.local_context);
        c->f8.local_context = 0;
    }
    free_affine_local_context(&(c->f9));
    if (c->f9.local_context != 0) {
        rt_free_func(c->f9.local_context);
        c->f9.local_context = 0;
    }
    free_softmax_local_context(&(c->f10));
    if (c->f10.local_context != 0) {
        rt_free_func(c->f10.local_context);
        c->f10.local_context = 0;
    }  
    free(context);
    return NN_ERROR_CODE_NOERROR;
}

float* nnablart_validation_input_buffer(void* context, int index)
{
    nnablart_validation_local_context_t* c = (nnablart_validation_local_context_t*)context;
    switch(index) {
        case 0: return (c->v0).data;
    }
    return 0;
}

float* nnablart_validation_output_buffer(void* context, int index)
{
    nnablart_validation_local_context_t* c = (nnablart_validation_local_context_t*)context;
    switch(index) {
        case 0: return (c->v19).data;
    }

    return 0;
}
float* nnablart_validation_param_buffer(void* context, int index)
{
    nnablart_validation_local_context_t* c = (nnablart_validation_local_context_t*)context;
    switch(index) {
        case 0: return (c->v2).data;
        case 1: return (c->v3).data;
        case 2: return (c->v7).data;
        case 3: return (c->v8).data;
        case 4: return (c->v12).data;
        case 5: return (c->v13).data;
        case 6: return (c->v16).data;
        case 7: return (c->v17).data;
    }
    return 0;
}
int nnablart_validation_inference(void* context)
{
    nnablart_validation_local_context_t* c = (nnablart_validation_local_context_t*)context;
    exec_mul_scalar(&(c->f0));
    exec_convolution(&(c->f1));
    exec_max_pooling(&(c->f2));
    exec_relu(&(c->f3));
    exec_convolution(&(c->f4));
    exec_max_pooling(&(c->f5));
    exec_relu(&(c->f6));
    exec_affine(&(c->f7));
    exec_relu(&(c->f8));
    exec_affine(&(c->f9));
    exec_softmax(&(c->f10));
    return NN_ERROR_CODE_NOERROR;
}
